batch_size: 128
config: configs/autosaved/config_2020_06_29_18_03.yml
data_dir: null
dataset: cifar10
epochs: 100
export_model_name: null
export_to_inference: null
export_to_trainable: null
initial_layers: thumbnail
model: meliusnet22_enas
num_classes: 10
num_gpus: 1
use_bmx_examples_datasets: true
verbose: true
