batch_size: 128
config: configs/default_config_melius22_mock.yml
data_dir: null
dataset: null
epochs: 5
export_model_name: model
export_to_inference: true
export_to_trainable: true
initial_layers: thumbnail
mock: cifar100
model: meliusnet22_enas
num_gpus: 0
num_workers: 0
training_name: null
use_bmx_examples_datasets: false
verbose: true
