batch_size: 128
config: configs/default_config_melius22_mock.yml
epochs: 5
export_model_name: model
export_to_inference: true
export_to_trainable: true
initial_layers: thumbnail
mock: cifar100
network: meliusnet22_enas
num_gpus: 0
train_data: null
training_name: null
val_data: null
verbose: true
