batch_size: 2
config: configs/default_config_resnet18_v1_enas_mock.yml
data_dir: null
dataset: null
epochs: 5
eval_split_percentage: 0.3
export_model_name: model
export_to_inference: true
export_to_trainable: true
initial_layers: thumbnail
mock: cifar100
model: resnet18_v1_enas
num_gpus: 1
num_workers: 0
training_name: null
use_bmx_examples_datasets: false
verbose: true
