batch_size: 128
config: configs/default_config_melius22_cifar100_imagenet_init.yml
data_dir: null
dataset: cifar100
epochs: 100
eval_split_percentage: 0.3
export_model_name: model
export_to_inference: true
export_to_trainable: true
initial_layers: imagenet
mock: null
model: meliusnet22_enas
num_gpus: 0
num_workers: 0
only_post_training_eval: true
training_name: null
use_bmx_examples_datasets: false
verbose: true
grad_cancel: 1.0
