batch_size: 128
config: configs/default_config_melius22_cifar100.yml
data_dir: null
dataset: cifar100
epochs: 100
eval_split_percentage: 0.5
export_model_name: model
export_to_inference: true
export_to_trainable: true
initial_layers: thumbnail
mock: null
model: meliusnet22_enas
num_gpus: 1
num_workers: 2
training_name: null
use_bmx_examples_datasets: false
verbose: true
