batch_size: 64
config: configs/default_config_melius22_imagenet.yml
data_dir: /mnt/ssd/datasets/ImageNet/extracted/rec
dataset: imagenet
epochs: 100
export_model_name: model
export_to_inference: true
export_to_trainable: true
initial_layers: imagenet
mock: null
model: meliusnet22_enas
num_gpus: 1
num_workers: 2
training_name: null
use_bmx_examples_datasets: false
augmentation: medium
verbose: true
